version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_transcendance
    volumes:
      - /var/folders/postgres:/data/postgres
    env_file:
      - ./backend/.env

networks:
  postgres:
    driver: bridge
